server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  # Servir arquivos HTML/CSS/JS diretamente
  location / {
    try_files $uri $uri/ =404;
  }

  # Proxy reverso para o backend (Spring Boot)
  location /api/ {
    proxy_pass http://spring_backend:8080/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}