services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/backup.sql:/docker-entrypoint-initdb.d/backup.sql

  backend:
    build: ./backend
    container_name: spring_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/meu_banco
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: senha
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "80:80"    # Mapeia a porta 80 local para a porta 80 do contêiner
      - "443:443"  # Mapeia a porta 443 local para a porta 443 do contêiner
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Certificados SSL
      - ./frontend/dist:/usr/share/nginx/html  # Arquivos estáticos do React
    depends_on:
      - backend


volumes:
  mysql_data:
