spring.application.name=SpringBoot2

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# era update. troquei pra evitar erros no banco
# agora é application-default para evitar conflito com application-test
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

ORS_API_KEY=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjNkN2ViMzBlYTZjOTRkZDg4MmI4MGVjNDA3ODgyODBhIiwiaCI6Im11cm11cjY0In0=